Implement server
codex-team/hawk.cloud-manager pull request #1
Opened 2020-08-21 14:17 UTC by f0m41h4u7

2020-08-25 15:53 UTC, kabachook requested changes

2020-08-25 15:53 UTC, kabachook commented on go.mod
> +	github.com/mailru/easyjson v0.7.6
Го оставим обычный json

2020-08-25 18:48 UTC, f0m41h4u7 commented on go.mod
> +	github.com/mailru/easyjson v0.7.6
ok

2020-08-25 19:10 UTC, kabachook approved these changes

2020-08-26 12:40 UTC, neSpecc requested changes

2020-08-26 12:40 UTC, neSpecc commented on internal/server/handlers.go
> +func (s *Server) handleTopology(c *gin.Context) {
а где доки к коду?

2020-08-27 16:24 UTC, n0str approved these changes

2020-08-31 14:53 UTC, neSpecc commented on cmd/manager/main.go
> +func main() {
нет доков

2020-08-31 14:53 UTC, neSpecc commented on cmd/manager/main.go
> +var (
нет доков

2020-08-31 14:53 UTC, neSpecc commented on internal/server/server.go
> +type Server struct {
нет доков

2020-08-31 14:53 UTC, neSpecc commented on internal/server/server.go
> +func New(addr string, config *config.PeerConfig) (*Server, error) {
тут и далее: нет доков

2020-08-31 18:09 UTC, neSpecc approved these changes

2020-08-31 18:17 UTC, merged