implement get and put request handlers
codex-team/hawk.cloud-manager pull request #4
Opened 2020-09-06 15:06 UTC by f0m41h4u7

2020-09-06 15:23 UTC, kabachook requested changes

2020-09-06 15:23 UTC, kabachook commented on internal/storage/yaml/yaml.go
> +	s.config = conf
Надо добавить сохранение обновленного конфига в yaml

2020-09-06 15:47 UTC, f0m41h4u7 commented on internal/storage/yaml/yaml.go
> +	s.config = conf
там есть метод `Save`. методы разные, чтобы удобнее было в тестах использовать

2020-09-11 09:04 UTC, kabachook requested changes

2020-09-11 09:04 UTC, kabachook commented on internal/server/handlers_test.go
> +func TestUpdateConfig(t *testing.T) {
Наверное надо написать комменты к тестам: что проверяют

2020-09-11 09:22 UTC, kabachook approved these changes

2020-09-11 09:22 UTC, n0str approved these changes

2020-09-11 09:23 UTC, merged